# Generated by Django 3.2 on 2022-09-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=30, verbose_name='影像名字')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='遥感影像')),
            ],
        ),
    ]
