# Generated by Django 3.2 on 2022-09-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imagetif',
            field=models.FileField(null=True, upload_to='imagetif', verbose_name='遥感影像原文件_tif'),
        ),
    ]
