# Generated by Django 3.2 on 2022-09-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackup', '0002_image_imagetif'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ioptif',
            field=models.FileField(null=True, upload_to='ioptif', verbose_name='遥感影像处理文件iop_tif'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='遥感影像处理后tiff2jpg'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imagetif',
            field=models.FileField(null=True, upload_to='imagetif', verbose_name='遥感影像原始文件rrs_tif'),
        ),
    ]
