# Generated by Django 3.2 on 2022-10-03 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appbackup', '0003_auto_20220930_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '所有image数据', 'verbose_name_plural': '所有image数据'},
        ),
        migrations.AddField(
            model_name='image',
            name='createtime',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 9, 43, 59, 659823, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='image',
            name='imagetif2jpg',
            field=models.FileField(null=True, upload_to='imagetif2jpg', verbose_name='遥感影像原始文件tif转jpg'),
        ),
    ]
