# Generated by Django 3.2 on 2022-10-03 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appbackup', '0004_auto_20221003_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='createtime',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
