# Generated by Django 3.2 on 2022-10-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackup', '0005_alter_image_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagetif2jpg',
            field=models.ImageField(blank=True, null=True, upload_to='imagetif2jpg', verbose_name='遥感影像原始文件tif转jpg'),
        ),
    ]
