# Generated by Django 3.2 on 2022-10-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackup', '0006_alter_image_imagetif2jpg'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='SPMimage',
            field=models.ImageField(blank=True, null=True, upload_to='SPMimage', verbose_name='遥感影像处理后tiff2jpg'),
        ),
        migrations.AddField(
            model_name='image',
            name='SPMtif',
            field=models.FileField(null=True, upload_to='SPMtif', verbose_name='遥感影像处理文件iop_tif'),
        ),
    ]
